apiVersion: v1
kind: ConfigMap 
metadata: 
  name: fiocfg 
  namespace: perf 
data: 
  fiojobs.fio: |- 
    ##making this fio file as place holder for new config
    [global] 
    ioengine=libaio 
    size=1GiB 
    name=test 
    direct=1 
    iodepth=128 
    ##----Begin 64k tests------- 
    [64k-write] 
    stonewall 
    blocksize=64k 
    filename=/data/fio.dat 
    readwrite=write 
    buffer_compress_percentage=50 end_fsync=1

    [64k-read] 
    stonewall 
    blocksize=64k 
    filename=/data/fio.dat 
    readwrite=read
 
    [64k-rand-write] 
    stonewall 
    blocksize=64k 
    filename=/data/fio.dat 
    readwrite=randwrite 
    buffer_compress_percentage=50 end_fsync=1
 
    [64k-rand-read] 
    stonewall 
    blocksize=64k 
    filename=/data/fio.dat 
    readwrite=randread 
    [64k-mix-rand-50-50] 
    stonewall 
    blocksize=64k 
    filename=/data/fio.dat 
    readwrite=randrw 
    rwmixread=50
    buffer_compress_percentage=50 end_fsync=1
 
    [64k-mix-rand-80-20] 
    stonewall 
    blocksize=64k 
    filename=/data/fio.dat 
    readwrite=randrw 
    rwmixread=80 
    buffer_compress_percentage=50 end_fsync=1
 
    [64k-mix-rand-20-80] 
    stonewall 
    blocksize=64k 
    filename=/data/fio.dat 
    readwrite=randrw 
    rwmixread=20 
    buffer_compress_percentage=50 end_fsync=1 
