apiVersion: v1
kind: Pod 
metadata: 
  name: fio-repl1
  namespace: perf 
  labels: 
    app: fio 
spec: 
  schedulerName: stork 
  containers: 
  - name: fio-write 
    image: dmonakhov/alpine-fio 
    securityContext: 
      privileged: true 
    volumeMounts: 
    - mountPath: /data 
      name: test-volume 
    - mountPath: /fiocfg 
      name: fiocfg 
    args: 
    - "sleep" 
    - "10000" 
    imagePullPolicy: IfNotPresent 
  restartPolicy: Never 
  volumes: 
  - name: test-volume 
    persistentVolumeClaim: 
      claimName: fio-repl1-pvc 
  - name: fiocfg 
    configMap: 
      name: fiocfg
