kind: StorageClass 
apiVersion: storage.k8s.io/v1 
metadata: 
  name: fio-repl1 
provisioner: kubernetes.io/portworx-volume
parameters: 
  repl: "1" 
  io_priority: "high" 
  cow_ondemand: "true" 
  allowVolumeExpansion: "true"
